name: flutter_application_2
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  percent_indicator: ^4.0.1
  flutter:
    sdk: flutter
  mobx: ^2.0.7+7
  flutter_mobx: ^2.0.6+3


  cupertino_icons: ^1.0.2
  navigator:
  sticky_headers: ^0.3.0
  carousel_slider: ^4.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.2.1
  mobx_codegen: ^2.0.7+2

  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
    - images/
    - assets/bottom_nav/
    - assets/
    - assets/similar_products/
    - assets/bottom_sheet_icons/
    - pdp_assets/images/
    - assets/images/


  fonts:
    - family: Proxima-Nova-A
      fonts:
        - asset: assets/fonts/Proxima-Nova-A.ttf
        - asset: assets/fonts/Proxima-Nova-A-Bold.ttf
        - asset: assets/fonts/Proxima-Nova-A-SemiBold.ttf
